[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["build", "--features=get_report"]

[tasks.test]
toolchain = "nightly"
command = "cargo"
args = ["test", "--features=get_report"]
dependencies = ["build"]
