# `cargo make test` is disabled for this crate so that 
# integration tests are not run with unit tests; specifically, tests
# in this crate should only be run after builds have completed in all
# other crates in the emuated workspace. 
#
# Tests in this crate can be invoked instead with `cargo make 
# integration` at the top level, or simply by running `cargo test` 
# inside this crate.

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["build", "--target=x86_64-unknown-linux-musl", "--features=get_report"]
dependencies = ["clean"]

[tasks.test]
toolchain = "nightly"
command = "cargo"
args = ["test", "--target=x86_64-unknown-linux-musl", "--features=get_report"]
dependencies = ["clean"]

#[tasks.test]
#disabled = true
